### ISSUE TITLE
TODO : Improved Search

### ISSUE THREAD

**Issue by rosmord** [rosmord/jsesh#2]
- search with wildcards (done)
- search in non-hieroglyphic texts
- fuzzy sign search (search using sign variants)
- both on in-file and multifile search
- full regexp search ? maybe later (the current system would allow it, but I'm not sure the users would use it ?)

**Comment by crolidge** [comment]
Would be nice the regexp search indeed....

**Comment by rosmord** [comment]
full regexp will wait a little bit - the code is almost done : the engine has been written for Ramses, and is currently used for wildcards ; and the basis for a GUI is available in Ramses too. Now, I prefer releasing the current version, which will cover most of the needs.
