### ISSUE TITLE
Error caused by language of OS

### ISSUE THREAD

**Issue by tahacelik20181** [rosmord/jsesh#35]
The Turkish (may more language) locale often causes issues because it has dotted and dotless I, which thus get uppercased and lowercased differently to most Latin-based alphabets. Fixing this requires specifying a locale in all instances where a string is uppercased or lowercased apart from human interface text.

The point of failure given:
https://github.com/rosmord/jsesh/blob/7d8d1c66cce21154cc3b69b151970c6832dda4ee/jsesh/src/main/java/jsesh/hieroglyphs/data/io/SignDescriptionBuilderToHieroglyphDatabaseAdapter.java#L64

_Originally posted by @Bikenkhet in https://github.com/rosmord/jsesh/issues/34#issuecomment-1033501174_

**Comment by rosmord** [comment]
I will have a look at the problem, and fix it ASAP.

**Comment by rosmord** [comment]
It's supposed to be fixed. Thanks for the suggested code.
